# Generated by Django 3.1 on 2021-01-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('utxt', models.TextField()),
                ('email', models.TextField()),
                ('ip', models.TextField()),
                ('country', models.TextField(default='')),
            ],
        ),
    ]
